name: DON-setup
on:
  push:
    branches:
      - main
    tags:
      - "DON_*"
  pull_request:
    branches:
      - main
jobs:
  Prerelease:
    if: github.repository == 'ehsanrashid/DON' && (github.ref == 'refs/heads/main' || (startsWith(github.ref_name, 'DON_') && github.ref_type == 'tag'))
    runs-on: ubuntu-latest
    needs: [Matrix]
    permissions:
      contents: write # For deleting/creating a prerelease
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Delete latest pre-release and tag
        if: github.ref_name == 'main'
        run: |
          # Verify required tools (should always be present on GitHub runners)
          command -v jq >/dev/null 2>&1 || { echo "jq not found"; exit 1; }
          command -v gh >/dev/null 2>&1 || { echo "gh not found"; exit 1; }
          # Get latest pre-release tag_name
          LATEST_PRERELEASE=$(gh release list --limit 10 --json tagName,isPrerelease \
            | jq -r '.[] | select(.isPrerelease == true) | .tagName' | head -n 1)

          if [ "$LATEST_PRERELEASE" != "null" ] && [ -n "$LATEST_PRERELEASE" ]; then
            echo "Deleting latest pre-release: $LATEST_PRERELEASE..."
            gh release delete "$LATEST_PRERELEASE" --cleanup-tag -y
          else
            echo "No pre-release found to delete."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get commit info
        run: |
          echo "COMMIT_SHA=$(git rev-parse HEAD | cut -c 1-8)" >> $GITHUB_ENV
          echo "COMMIT_DATE=$(git show -s --date=format:'%Y%m%d' --format=%cd HEAD)" >> $GITHUB_ENV

      # Make sure that an old ci that still runs on master doesn't recreate a prerelease
      - name: Check Pullable Commits
        run: |
          git fetch origin main
          CHANGES=$(git rev-list HEAD..origin/main --count)
          echo "CHANGES=$CHANGES" >> $GITHUB_ENV

      # Determine if this is an official release
      - name: Official Release?
        run: |
          if git log -1 --pretty=%B | grep -q "Official release version of DON"; then
            echo "OFFICIAL_RELEASE=true" >> $GITHUB_ENV
            echo "This is an official release."
          else
            echo "OFFICIAL_RELEASE=false" >> $GITHUB_ENV
            echo "This is NOT an official release."
          fi

      # Create pre-release
      - name: Create Pre-release
        if: github.ref_name == 'main' && env.CHANGES == '0' && env.OFFICIAL_RELEASE == 'false'
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        with:
          name: DON dev-${{ env.COMMIT_DATE }}-${{ env.COMMIT_SHA }}
          tag_name: DON-dev-${{ env.COMMIT_DATE }}-${{ env.COMMIT_SHA }}
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
      # Create official release
      - name: Create Official Release
        if: startsWith(github.ref_name, 'DON_') && github.ref_type == 'tag'
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        with:
          name: DON ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          prerelease: false
          body: Official release version of DON
          token: ${{ secrets.GITHUB_TOKEN }}
  Matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      arm_matrix: ${{ steps.set-arm-matrix.outputs.arm_matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - id: set-matrix
        run: |
          TASKS=$(echo $(cat .github/ci/matrix.json) )
          echo "MATRIX=$TASKS" >> $GITHUB_OUTPUT
      - id: set-arm-matrix
        run: |
          TASKS_ARM=$(echo $(cat .github/ci/arm_matrix.json) )
          echo "ARM_MATRIX=$TASKS_ARM" >> $GITHUB_OUTPUT
  # Testing Jobs
  IWYU:
    uses: ./.github/workflows/iwyu.yml
  Sanitizers:
    if: ${{ always() }}
    uses: ./.github/workflows/sanitizers.yml
  Tests:
    if: ${{ always() }}
    uses: ./.github/workflows/tests.yml
  Matetrack:
    if: ${{ always() }}
    uses: ./.github/workflows/matetrack.yml
  Games:
    if: ${{ always() }}
    uses: ./.github/workflows/games.yml
  CompilerCheck:
    if: ${{ always() }}
    uses: ./.github/workflows/avx2_compilers.yml
  # Release Jobs
  Compilation:
    needs: [Matrix, Sanitizers, Tests, Matetrack, Games, CompilerCheck]
    uses: ./.github/workflows/compilation.yml
    with:
      matrix: ${{ needs.Matrix.outputs.matrix }}
  ARMCompilation:
    needs: [Matrix, Sanitizers, Tests, Matetrack, Games, CompilerCheck]
    uses: ./.github/workflows/arm_compilation.yml
    with:
      matrix: ${{ needs.Matrix.outputs.arm_matrix }}
  Binaries:
    if: github.repository == 'ehsanrashid/DON'
    needs: [Prerelease, Matrix, Compilation]
    uses: ./.github/workflows/upload_binaries.yml
    with:
      matrix: ${{ needs.Matrix.outputs.matrix }}
    permissions:
      contents: write # For deleting/creating a (pre)release
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  ARM_Binaries:
    if: github.repository == 'ehsanrashid/DON'
    needs: [Prerelease, Matrix, ARMCompilation]
    uses: ./.github/workflows/upload_binaries.yml
    with:
      matrix: ${{ needs.Matrix.outputs.arm_matrix }}
    permissions:
      contents: write # For deleting/creating a (pre)release
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
